---
- name: Развертывание системы мониторинга Zabbix
  hosts: all
  become: yes
  vars:
    # База данных
    db_root_pass: "RootPassword"     # Пароль root для MariaDB
    zabbix_db_pass: "ZabbixDBPass"   # Пароль пользователя zabbix
    
    # Твои настройки PHP
    php_memory_limit: "16M"
    php_timezone: "Europe/Moscow"
    
    # Сеть
    zabbix_server_ip: "{{ groups['zabbix_server'][0] }}"

  tasks:
    # ---------------------------------------------------------
    # 1. РЕПОЗИТОРИИ (EPEL, Remi, Zabbix)
    # ---------------------------------------------------------
    - name: Установка EPEL и Remi репозиториев
      yum:
        name:
          - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
          - https://rpms.remirepo.net/enterprise/remi-release-7.rpm
        state: present

    - name: Включение PHP 7.4 (Remi)
      command: yum-config-manager --enable remi-php74
      args:
        creates: /etc/yum.repos.d/remi-php74.repo

    - name: Установка Zabbix репозитория
      yum:
        name: "https://repo.zabbix.com/zabbix/6.0/rhel/7/x86_64/zabbix-release-6.0-4.el7.noarch.rpm"
        state: present

    # ---------------------------------------------------------
    # 2. УСТАНОВКА ПАКЕТОВ
    # ---------------------------------------------------------
    - name: Установка необходимых пакетов (Server, Frontend, Agent)
      yum:
        name:
          - mariadb-server
          - zabbix-server-mysql
          - zabbix-web-mysql
          - zabbix-apache-conf
          - zabbix-sql-scripts
          - zabbix-agent
          - MySQL-python  # Обязательно для работы модулей mysql_*
        state: present

    # ---------------------------------------------------------
    # 3. НАСТРОЙКА БАЗЫ ДАННЫХ (Исправлено: разделено на разные задачи)
    # ---------------------------------------------------------
    - name: Запуск MariaDB
      systemd:
        name: mariadb
        state: started
        enabled: yes

    - name: Создание базы данных zabbix
      mysql_db:
        name: zabbix
        encoding: utf8mb4
        collation: utf8mb4_bin
        state: present
      register: db_created

    - name: Создание пользователя zabbix
      mysql_user:
        name: zabbix
        password: "{{ zabbix_db_pass }}"
        priv: "zabbix.*:ALL"
        state: present

    - name: Проверка наличия таблиц в БД
      command: mysql -NBe "USE zabbix; SHOW TABLES;"
      register: tables_exist
      changed_when: false

    - name: Импорт схемы базы данных
      shell: "zcat /usr/share/doc/zabbix-sql-scripts/mysql/server.sql.gz | mysql -uzabbix -p{{ zabbix_db_pass }} zabbix"
      when: tables_exist.stdout == ""

    # ---------------------------------------------------------
    # 4. КОНФИГУРАЦИЯ СЕРВЕРА И PHP
    # ---------------------------------------------------------
    - name: Установка пароля БД в конфиге Zabbix Server
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: '^# DBPassword='
        line: "DBPassword={{ zabbix_db_pass }}"

    - name: Настройка параметров PHP (Memory Size и Timezone)
      lineinfile:
        path: /etc/opt/rh/rh-php74/php-fpm.d/zabbix.conf
        regexp: "{{ item.regex }}"
        line: "{{ item.line }}"
      loop:
        - { regex: 'php_value\[memory_limit\]', line: "php_value[memory_limit] = {{ php_memory_limit }}" }
        - { regex: 'php_value\[date.timezone\]', line: "php_value[date.timezone] = {{ php_timezone }}" }

    # ---------------------------------------------------------
    # 5. НАСТРОЙКА АГЕНТА (Снятие метрик системы)
    # ---------------------------------------------------------
    - name: Настройка Zabbix Agent
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: "{{ item.regex }}"
        line: "{{ item.line }}"
      loop:
        - { regex: '^Server=', line: "Server={{ zabbix_server_ip }}" }
        - { regex: '^ServerActive=', line: "ServerActive={{ zabbix_server_ip }}" }
        - { regex: '^Hostname=', line: "Hostname={{ ansible_hostname }}" }

    # ---------------------------------------------------------
    # 6. БЕЗОПАСНОСТЬ И ЗАПУСК
    # ---------------------------------------------------------
    - name: Открытие портов в Firewalld (80, 10050, 10051)
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      loop: ['80/tcp', '10050/tcp', '10051/tcp']
      ignore_errors: yes

    - name: Разрешение Zabbix в SELinux
      seboolean:
        name: zabbix_can_network
        state: yes
        persistent: yes
      ignore_errors: yes

    - name: Перезапуск и включение всех сервисов
      systemd:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      loop:
        - zabbix-server
        - zabbix-agent
        - httpd
        - rh-php74-php-fpm
        - mariadb
